Microsoft.AspNet.NodeServices/HostingModels/OutOfProcessNodeInstance.cs
Added Started console message
Captured possible exception from node process
=> Restored Killed console message

Microsoft.AspNet.NodeServices/Content/Node/entrypoint-http.js, Microsoft.AspNet.NodeServices/HostingModels/HttpNodeInstance.cs
I updated the old express calls to use the ones provided by the base node framework. 
There are two other changes I wanted to suggest as well. If a module is not found an error is thrown which results in a non-graceful shutdown of the process. This in turn results in a generic exception in .NET which does not give any indication of the error that actually occurred within the node process.
```node
throw new Error('The module "' + resolvedPath + '" has no export named "' + bodyJson.exportedFunctionName + '"');
``` 
This also applies to the logic used in `react-rendering.js`. I would propose ensuring that all errors bubble up to the client without causing the process to end unexpectedly i.e. wrapping the logic inside of a try/catch block and sending the error via the http pipeline before …
=> Replace express with native node calls

src/Microsoft.AspNet.SpaServices/npm/aspnet-webpack/src/WebpackDevMiddleware.ts
Add check for string entry - if so, replace main entry with new array of hot middleware and old entry.
=> Fix issue: entry.main.unshift is not a function Closes #56

src/Microsoft.AspNetCore.SpaServices/npm/aspnet-webpack/src/WebpackDevMiddleware.ts
- Parses publicPath as an URL and returns the path of that URL to be able to cope with absolute URLs
=> Makes it possible to use absolute paths for publicPath in weback.config

src/Microsoft.AspNetCore.NodeServices/HostingModels/OutOfProcessNodeInstance.cs
When investigating #247 I noticed that the `NODE_PATH` would look something like:
`C:\tmp\.nvm\v6.3.1\node_modules:C:\_code\project\node_modules`
The problem is that the path separator is `:` not `;`.
This fix have resolve the issue in my testing.
1. Create a new project using the yeoman generator
2. Enable server side rendering
3. Set `NODE_PATH` to have a value (eg: `C:\tmp`)
4. Run the application and experience the error described in #247 
5. Apply patch
6. Run the application successfully
=> FIxing path separator to address #247

src/Microsoft.AspNetCore.NodeServices/HostingModels/SocketNodeInstance.cs
Fixes sending invocation info to the node process when it is first created for the SocketNodeInstance, when serializing >30MB of JSON text and using 32-bit IIS Express (with a .NET Framework 4.5.2 app), which would otherwise result in an OutOfMemoryException at the GetBytes method.
This fix serializes the invocationInfo into a JSON string directly to the stream without double-handling it as a string to reduce the memory footprint of the application. It uses the NewtonsoftJson JsonTextWriter to handle serialization to the stream.
The underlying stream is kept open while the writers are disposed by creating the StreamWriter with 'true' as the last parameter of its constructor (this also requires specifying the buffer size, so I've copied the size used in a method below), and setting the …
=> Serialize node invocationInfo JSON directly to stream to avoid running out of memory

samples/misc/Webpack/webpack.config.dev.js, samples/misc/Webpack/webpack.config.prod.js, src/Microsoft.AspNetCore.SpaServices/README.md, templates/Angular2Spa/webpack.config.js, templates/Angular2Spa/webpack.config.vendor.js, templates/AureliaSpa/webpack.config.js, templates/AureliaSpa/webpack.config.vendor.js, templates/KnockoutSpa/ClientApp/components/app-root/app-root.ts, templates/KnockoutSpa/ClientApp/webpack-component-loader.ts, templates/KnockoutSpa/webpack.config.js, templates/KnockoutSpa/webpack.config.vendor.js, templates/ReactReduxSpa/webpack.config.js, templates/ReactReduxSpa/webpack.config.vendor.js, templates/ReactSpa/webpack.config.js, templates/ReactSpa/webpack.config.vendor.js, templates/WebApplicationBasic/webpack.config.js, templates/WebApplicationBasic/webpack.config.vendor.js
Addresses issue #444 by explicitly adding a `-loader` suffix to all Webpack loader references.
=> Add '-loader' suffix to all Webpack loader references

templates/ReactReduxSpa/.babelrc
One of the big features in Webpack 2 is tree shaking. Modified config to enable this in client bundle output.
Debated adding logic to common config as server bundle still needs module transform, but in the end decided it was probably clearer for developers to just pull out module rules from common and have client and server config define separately.
=> Modifies webpack config in ReactReduxSpa template to enable treeshaking

templates/ReactReduxSpa/webpack.config.js, templates/ReactSpa/webpack.config.js
Added babel-loader caching which significantly improves build times. This is also used in the create-react-app template.
First run:
```
$ webpack
(node:2164) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
Hash: f657172a5ca6dcdcb4ddfb908cb42dfef18c1ea5
Version: webpack 2.2.1
Child
Hash: f657172a5ca6dcdcb4dd
Time: 11244ms
Asset      Size  Chunks             Chunk Names
main-client.js   49.7 kB       0  [emitted]  main-client
site.css   1.56 kB       0  [emitted]  main-client
main-client.js.map   31.6 kB       0  [emitted]  main-client
site.css.map  85 bytes       0  [emitted]  main-client
Child …
```
=> Added babel-loader caching to improve subsequent build times.

samples/misc/LatencyTest/LatencyTest.csproj
`Project Sdk="Microsoft.NET.Sdk"` needs `<OutputType>exe</OutputType>` or it thinks its a library
=> Console type needs exe

src/Microsoft.AspNetCore.SpaServices/npm/aspnet-webpack/src/WebpackDevMiddleware.ts
This enables Docker HMR workflow and the workaround mentioned in this comment: https://github.com/aspnet/JavaScriptServices/issues/806#issuecomment-290081291
=> Fix watchOptions in webpack.config.js being ignored by WebpackDevMiddleware

templates/AureliaSpa/ClientApp/app/components/app/app.ts, templates/AureliaSpa/ClientApp/boot.ts, templates/AureliaSpa/Startup.cs, templates/AureliaSpa/package.json, templates/AureliaSpa/tsconfig.json, templates/AureliaSpa/webpack.config.js, templates/AureliaSpa/webpack.config.vendor.js
* Updates to new aurelia-webpack-plugin (Webpack 2). 
* Enables webpack hmr support by default
*todo:*
=> Update Aurelia SPA template

README.md
I keep searching for this very useful MSDN blog link.
=> Add blog link

templates/ReactReduxSpa/ClientApp/components/Counter.tsx, templates/ReactReduxSpa/ClientApp/components/FetchData.tsx, templates/ReactReduxSpa/ClientApp/components/Home.tsx, templates/ReactReduxSpa/ClientApp/components/Layout.tsx, templates/ReactReduxSpa/ClientApp/components/NavMenu.tsx, templates/ReactSpa/ClientApp/components/Counter.tsx, templates/ReactSpa/ClientApp/components/FetchData.tsx, templates/ReactSpa/ClientApp/components/Home.tsx, templates/ReactSpa/ClientApp/components/Layout.tsx, templates/ReactSpa/ClientApp/components/NavMenu.tsx
The React templates used `any` and `void` as State and Property types for React.Component, even though it should be `{}`.
=> Templates: update React's component's State and Property type

README.md
Doing this due to a Stack Overflow question where a dev thought this project doesn't support Aurelia simply b/c this Readme file didn't include it.  Went ahead and added Vue as well for completeness.
=> Add Aurelia and Vue to framework list

src/Microsoft.AspNetCore.NodeServices/HostingModels/OutOfProcessNodeInstance.cs
Following up on #804 
Fixes the debugger which causes the .NET Core app to crash due to a Node warning. 
Unfortunately it's hard to make this really future proof, because the wording and structure of the warnings regarding debugging could easily change in future versions. I still think it would be nice to be able to treat all warnings from Node differently from errors, but no idea how to approach that. Cause for a separate discussion I suppose.
=> Fix Node debugging by catching warning

src/Microsoft.AspNetCore.SpaServices/README.md
Since the CSPROJ project system is the latest & greatest for ASP.NET Core, the `project.json` file reference should probably be removed.
=> Update SpaServices NuGet package installation requirement

appveyor.yml, src/Microsoft.AspNetCore.NodeServices/Content/Node/entrypoint-http.js, src/Microsoft.AspNetCore.NodeServices/TypeScript/HttpNodeInstanceEntryPoint.ts, src/Microsoft.AspNetCore.NodeServices/TypeScript/Util/PatchModuleResolutionLStat.ts, templates/AngularSpa/AngularSpa.csproj, templates/AureliaSpa/AureliaSpa.csproj, templates/KnockoutSpa/KnockoutSpa.csproj, templates/ReactReduxSpa/ReactReduxSpa.csproj, templates/ReactSpa/ReactSpa.csproj, templates/VueSpa/VueSpa.csproj
It's not great to have to patch Node internals like this, but it's the best we've got in the short term. See #1101 for details of the problem this solves.
This logic was tested on Node versions 0.12.0, 4.6.2, 6.11.0, and 8.1.3 (Windows 10, 64 bit).
Longer term, we need to work with the Node folks to get a proper fix into Node itself and then make this patching logic conditional on older versions of Node.
=> On Windows, patch Node's lstat to work around permissions error. Fixes #1101

src/Microsoft.AspNetCore.SpaServices/Webpack/ConditionalProxyMiddleware.cs, src/Microsoft.AspNetCore.SpaServices/Webpack/WebpackDevMiddleware.cs
Previously the proxying logic handled nonempty `PathBase` values incorrectly. Also it didn't allow for Webpack `publicPath` values being set dynamically at runtime via `<base href>`. Both of these are needed for HMR to work correctly if the app is hosted in a virtual directory.
This change, along with an update to the `aspnet-webpack` NPM package, will fix #488
=> Fix webpack HMR proxying logic for apps running on non-root URLs (e.g., full IIS virtual directories)

src/Microsoft.AspNetCore.NodeServices/Content/Node/entrypoint-http.js, src/Microsoft.AspNetCore.NodeServices/TypeScript/Util/PatchModuleResolutionLStat.ts
After further testing, I've found a scenario where the existing patching logic was inadequate because of an optional param it wasn't passing through.
=> Complete the lstat patching for #1101

src/Microsoft.AspNetCore.NodeServices/HostingModels/HttpNodeInstance.cs
HttpClient defaults to 100 seconds. If InvocationTimeoutMilliseconds is greater than the default of the HttpClient, the task will fail with a Task was canceled exception.
=> HttpNodeInstance - Added Timeout to HttpClient to always be longer than the InvocationTimeoutMilliseconds

src/Microsoft.AspNetCore.SpaServices/Webpack/WebpackDevMiddleware.cs
This fixes middleware when consumers override serializer defaults settings via `JsonConvert.DefaultSettings` which would break webpack options passed to node. 
Since it's expected to be as Pascal case, it's safer to specifically specify it, and in our case we had it default to camelCase which was silently breaking it (and it was quite hard to figure it out).
=> fix(webpack): fix middleware to specifically serialize options as pascal case

src/Microsoft.AspNetCore.SpaServices/Prerendering/SpaPrerenderingExtensions.cs
...which uses [the `ISupportRequiredService` optimization](https://github.com/aspnet/DependencyInjection/blob/88c3bd6fe2786dd759b4a6c6d7c410e895336b6c/src/DI.Abstractions/ServiceProviderServiceExtensions.cs#L50-L54)
=> Use built-in GetRequiredService<T>

.appveyor.yml, korebuild.json
AppVeyor isn't actually building the repo because the default AppVeyor image is VS 2015, not 2017. 
Changes:
- update appveyor to vs2017
- execute a default build with korebuild
- add 'nodejs' as a required toolset in korebuild.json. This ensures nodejs is available on the machine. (Assuming this is required so tests can run)
=> Update appveyor to run korebuild

src/Microsoft.AspNetCore.SpaServices/README.md
Changing hot module replacement install from dependencies to devDependencies.  Raised in this Issue: https://github.com/aspnet/JavaScriptServices/issues/1409
=> Change HMR install to devDependencies

src/Microsoft.AspNetCore.SpaServices/npm/domain-task/src/main.ts
=> Returning provided promise in `addTask`

CONTRIBUTING.md, README.md, src/Microsoft.AspNetCore.NodeServices/README.md, src/Microsoft.AspNetCore.SpaServices/README.md, src/Microsoft.AspNetCore.SpaServices/Webpack/ConditionalProxyMiddleware.cs
I noticed that a lot of links in the readme actually lead to 404 pages because branch dev is missing (d742bea01e2d3179e142d708dc5be18ed2784432).
This just changes "dev" to "master", not sure if that's correct or desirable so feel free to close this again if not correct or necessary.
=> Fix links that assumed branch "dev" exists (which doesn't)

src/Microsoft.AspNetCore.NodeServices.Sockets/Content/Node/entrypoint-socket.js, src/Microsoft.AspNetCore.NodeServices.Sockets/package-lock.json, src/Microsoft.AspNetCore.NodeServices.Sockets/package.json, src/Microsoft.AspNetCore.NodeServices.Sockets/webpack.config.js, src/Microsoft.AspNetCore.NodeServices/Content/Node/entrypoint-http.js, src/Microsoft.AspNetCore.NodeServices/TypeScript/HttpNodeInstanceEntryPoint.ts, src/Microsoft.AspNetCore.NodeServices/package-lock.json, src/Microsoft.AspNetCore.NodeServices/package.json, src/Microsoft.AspNetCore.NodeServices/webpack.config.js, src/Microsoft.AspNetCore.SpaServices/Content/Node/prerenderer.js, src/Microsoft.AspNetCore.SpaServices/Content/Node/webpack-dev-middleware.js, src/Microsoft.AspNetCore.SpaServices/TypeScript/Prerenderer.ts, src/Microsoft.AspNetCore.SpaServices/package-lock.json, src/Microsoft.AspNetCore.SpaServices/package.json, src/Microsoft.AspNetCore.SpaServices/webpack.config.js
Previously they assumed you were using versions of TypeScript and Webpack that are by now rather outdated. This PR:
1. Updates to the latest TypeScript/Webpack
2. Includes `package-lock.json` files to lock down exactly which versions should be used, so it won't break in the future if TypeScript/Webpack themselves introduce breaking changes
=> Update NodeServices/SpaServices/NodeServices.Sockets to build using latest TypeScript and Webpack

scripts/Regenerate-JSFiles.ps1, src/Microsoft.AspNetCore.NodeServices.Sockets/Content/Node/entrypoint-socket.js, src/Microsoft.AspNetCore.NodeServices.Sockets/TypeScript/VirtualConnections/VirtualConnection.ts, src/Microsoft.AspNetCore.NodeServices.Sockets/TypeScript/VirtualConnections/VirtualConnectionServer.ts, src/Microsoft.AspNetCore.NodeServices.Sockets/package-lock.json, src/Microsoft.AspNetCore.NodeServices.Sockets/package.json, src/Microsoft.AspNetCore.NodeServices.Sockets/webpack.config.js, src/Microsoft.AspNetCore.NodeServices/Content/Node/entrypoint-http.js, src/Microsoft.AspNetCore.NodeServices/TypeScript/HttpNodeInstanceEntryPoint.ts, src/Microsoft.AspNetCore.NodeServices/package-lock.json, src/Microsoft.AspNetCore.NodeServices/package.json, src/Microsoft.AspNetCore.NodeServices/webpack.config.js, src/Microsoft.AspNetCore.SpaServices/Content/Node/prerenderer.js, src/Microsoft.AspNetCore.SpaServices/Content/Node/webpack-dev-middleware.js, src/Microsoft.AspNetCore.SpaServices/TypeScript/Prerenderer.ts, src/Microsoft.AspNetCore.SpaServices/package-lock.json, src/Microsoft.AspNetCore.SpaServices/package.json, src/Microsoft.AspNetCore.SpaServices/webpack.config.js
Fixes #1668.
All the whitespace stuff was done by VSCode, but it appears to be correct to me, so I'm not going to fight it unless @SteveSandersonMS objects.
=> Don't use depricated constructor

src/Microsoft.AspNetCore.NodeServices/Configuration/NodeServicesOptions.cs, src/Microsoft.AspNetCore.SpaServices.Extensions/Util/LoggerFinder.cs
Using this type for 2.2 is fine I'll make a full fix in 3.0.
=> Remove obsolete API usage

build/dependencies.props, samples/misc/LatencyTest/LatencyTest.csproj, samples/misc/NodeServicesExamples/NodeServicesExamples.csproj, samples/misc/Webpack/Webpack.csproj, src/Microsoft.AspNetCore.NodeServices/Configuration/NodeServicesOptions.cs, src/Microsoft.AspNetCore.NodeServices/Microsoft.AspNetCore.NodeServices.csproj, src/Microsoft.AspNetCore.SpaServices.Extensions/Util/LoggerFinder.cs
Falling back to creating instances of console logger is bad practice. Each of them would create a new writing thread and background queue. In addition, ConsoleLogger type is becoming private.
cc @Eilon
Technically it's a breaking change for customers who didn't have logging configured at all and used JavaScriptServices.
=> Do not fallback to creating console logger
